apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-broker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DmytroKrynytsyn/llm-broker.git
    targetRevision: HEAD
    path: helm/llm-broker
  destination:
    server: https://kubernetes.default.svc
    namespace: llm-broker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true