image:
  repository: dkrinitsyn/llm-broker
  tag: "20260531182043"
  pullPolicy: Always

replicaCount: 1

env:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local/"
  OLLAMA_URL: "http://kbrain2:11434"
  DEFAULT_MODEL: "qwen3:30b-a3b-instruct-2507-q4_K_M"
  OLLAMA_TIMEOUT: "1800"
  METRICS_PORT: "8000"

namespace: llm-broker