image:
  repository: dkrinitsyn/llm-broker
  tag: "20260605060610"
  pullPolicy: Always

replicaCount: 1

env:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local/"
  OLLAMA_URL: "http://kbrain2:11434"
  OLLAMA_TIMEOUT: "28800"
  METRICS_PORT: "8000"

namespace: llm-broker