image:
  repository: dkrinitsyn/llm-broker
  tag: "20260530151528"
  pullPolicy: Always

replicaCount: 1

env:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local/"
  OLLAMA_URL: "http://kbrain2:11434"
  DEFAULT_MODEL: "qwen2.5:32b-instruct-q2_K"
  OLLAMA_TIMEOUT: "1800"
  METRICS_PORT: "8000"

namespace: llm-broker